spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/trood
    username: postgres
    password: "1"
  jpa:
    hibernate:
      ddl-auto: create # Hibernate will create and update the tables itself
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
